version: "3.3"
services:
  postgresWeatherDB:
    image: postgres:13
    container_name: "postgresWeatherDB"
    environment:
      - POSTGRES_DB=WeatherDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=stein
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  weather-app:
    build: ./app
    container_name: "weather-app"
    environment: 
      - NODE_ENV=development
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - "postgresWeatherDB"
    ports:
      - "3000:3000"