version: "3.3"
services:
  postgres:
    image: postgres:13
    container_name: "postgresCitiesWeather"
    environment:
      - POSTGRES_DB=CitiesWeather
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=stein
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  weather-app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    links:
      - "postgres"
    # ports:
    #   - "5000:5000"